services:
  _defaults:
    autowire: true
    autoconfigure: true

  DevAway\KartCompetition\Shared\Domain\Bus\CommandBus:
    class: 'DevAway\KartCompetition\Shared\Infrastructure\Bus\TacticianCommandBus'

  DevAway\KartCompetition\Competition\Application\Command\Handler\CreateRaceHandler:
    tags:
      - { name: tactician.handler, command: DevAway\KartCompetition\Competition\Application\Command\CreateRace, bus: default }

  DevAway\KartCompetition\Competition\Application\Command\Handler\FindAllRaceHandler:
    tags:
      - { name: tactician.handler, command: DevAway\KartCompetition\Competition\Application\Command\ListRacesByCriteria, bus: default }

  DevAway\KartCompetition\Competition\Application\Command\Handler\ListPilotsByCriteriaHandler:
    tags:
      - { name: tactician.handler, command: DevAway\KartCompetition\Competition\Application\Command\ListPilotsByCriteria, bus: default }