doctrine:
    dbal:
        dbname:           '%env(resolve:COMPETITION_DATABASE_DBNAME)%'
        user:             '%env(resolve:COMPETITION_DATABASE_USER)%'
        password:         '%env(resolve:COMPETITION_DATABASE_PASSWORD)%'
        host:             '%env(resolve:COMPETITION_DATABASE_HOST)%'
        server_version:   '%env(resolve:COMPETITION_DATABASE_VERSION)%'

        types:
            IdType: DevAway\KartCompetition\Competition\Infrastructure\Repository\Persistence\Doctrine\CustomType\Competition\IdType
            IdPilotType: DevAway\KartCompetition\Competition\Infrastructure\Repository\Persistence\Doctrine\CustomType\Competition\IdPilotType
            PointsType: DevAway\KartCompetition\Competition\Infrastructure\Repository\Persistence\Doctrine\CustomType\Competition\PointsType
            RaceNameType: DevAway\KartCompetition\Competition\Infrastructure\Repository\Persistence\Doctrine\CustomType\Competition\RaceNameType
            TimeType: DevAway\KartCompetition\Competition\Infrastructure\Repository\Persistence\Doctrine\CustomType\Competition\TimeType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            DevAway\KartCompetition\Competition\Domain:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/KartCompetition/Competition/Infrastructure/Repository/Persistence/Doctrine/Entity'
                prefix: 'DevAway\KartCompetition\Competition\Domain\Entity'
                alias: DevAway
