get_race:
  path: /{version}/race/{id}
  controller: DevAway\KartCompetition\Competition\Infrastructure\EntryPoint\Controller\GetRaces
  methods: GET
  requirements:
    version: v1

post_race:
  path: /{version}/race
  controller: DevAway\KartCompetition\Competition\Infrastructure\EntryPoint\Controller\PostRaces
  methods: POST
  requirements:
    version: v1