get_race:
  path: /{version}/race/{id}
  controller: DevAway\KartCompetition\Competition\Infrastructure\EntryPoint\Controller\GetRaces
  methods: GET
  requirements:
    version: v1

post_race:
  path: /{version}/race
  controller: DevAway\KartCompetition\Competition\Infrastructure\EntryPoint\Controller\PostRace
  methods: POST
  requirements:
    version: v1


post_races:
  path: /{version}/race
  controller: DevAway\KartCompetition\Competition\Infrastructure\EntryPoint\Controller\PostRaces
  methods: POST
  requirements:
    version: v1

get_competicion_general_races:
  path: /{version}/general
  controller: DevAway\KartCompetition\Competition\Infrastructure\EntryPoint\Controller\GetGeneralCompetitionRaces
  methods: GET
  requirements:
    version: v1