# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

imports:
    - { resource: services/commandbus.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DevAway\KartCompetition\Competition\Infraestructure\EntryPoint\Controller\:
        resource: '../src/KartCompetition/Competition/Infraestructure/EntryPoint/Controller'
        tags: ['controller.service_arguments']

    DevAway\KartCompetition\Competition\Application\:
        resource: '../src/KartCompetition/Competition/Application'
        exclude: '../src/KartCompetition/Competition/Application/{Command}'



