services:
  _defaults:
    public: true

#  DevAway\KartCompetition\Competition\Domain\Repository\RaceRepository:
#    class: 'DevAway\KartCompetition\Competition\Infrastructure\Repository\MysqlRaceRepository'
#    arguments: ['@doctrine.orm.entity_manager']

  DevAway\Tests\Integration\KartCompetition\Shared\Infrastructure\DataFixtures\MysqlFixtureLoader:
    class: 'DevAway\Tests\Integration\KartCompetition\Shared\Infrastructure\DataFixtures\MysqlFixtureLoader'
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@DevAway\KartCompetition\Competition\Domain\Repository\RaceRepository'
      - '@DevAway\KartCompetition\Competition\Domain\Repository\PilotRepository'