parameters:

imports:
    - { resource: services/commandbus.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DevAway\KartCompetition\Shared\Infrastructure\:
        resource: '../src/KartCompetition/Shared/Infrastructure/*'

    DevAway\KartCompetition\Competition\Application\:
        resource: '../src/KartCompetition/Competition/Application'
        exclude: '../src/KartCompetition/Competition/Application/{Command}'

    DevAway\KartCompetition\Competition\Infrastructure\EntryPoint\Controller\:
        resource: '../src/KartCompetition/Competition/Infrastructure/EntryPoint/Controller'
        tags: ['controller.service_arguments']

    DevAway\KartCompetition\Competition\Domain\Repository\RaceRepository:
        class: 'DevAway\KartCompetition\Competition\Infrastructure\Repository\MysqlRaceRepository'
        arguments: ['@doctrine.orm.entity_manager']

    DevAway\KartCompetition\Competition\Domain\Repository\PilotRepository:
        class: 'DevAway\KartCompetition\Competition\Infrastructure\Repository\MysqlPilotRepository'
        arguments: ['@doctrine.orm.entity_manager']



